NewMap2_MapScripts::
	.byte 0

Map2_Growlithtrianer::
	trainerbattle_double TRAINER_DAISY, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_FisherTrainer1::
	trainerbattle_double TRAINER_IVAN, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_FisherTrainer2::
	trainerbattle_double TRAINER_ANDREW, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_Old_ladyTrainer2::
	trainerbattle_double TRAINER_ROSE_1, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_Traner1::
	trainerbattle_double TRAINER_ROSE_1, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_Traner2::
	trainerbattle_double TRAINER_ROSE_1, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_Traner3::
	trainerbattle_double TRAINER_ROSE_1, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_Traner4::
	trainerbattle_double TRAINER_ROSE_1, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_Traner5::
	trainerbattle_double TRAINER_ROSE_1, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_Traner6::
	trainerbattle_double TRAINER_ROSE_1, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_Traner7::
	trainerbattle_double TRAINER_ROSE_1, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_Traner8::
	trainerbattle_double TRAINER_ROSE_1, Map2_GrowlithtrianerIntro, Map2_GrowlithtrianerOutro,Map2_GrowlithtrianerMon
	end

Map2_GrowlithtrianerIntro:
.string "You'll never beat me!$"

Map2_GrowlithtrianerOutro:
.string "I can't believe it!$"

Map2_GrowlithtrianerMon:
.string "You have to have more pokemon!$"
